### ISSUE TITLE
Subtitle for project has broken link to https://kortemmelab.ucsf.edu/benchmarks

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#1]

**Comment by spiderbaby** [comment]
Yes, this is intentional (the link, not the broken state). The website is currently hosted on our computational server but I will add a redirect to that from the address above later. The final home for the website will be on kortemmelab.ucsf.edu. I'll leave the ticket open as a reminder.

**Comment by spiderbaby** [comment]
Fixed now.
