### ISSUE TITLE
Running process_specificity() gives deprecation warning, use process_seqtol() instead

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#10]
In analysis/README.rst, change process_specificity() to process_seqtol()

**Comment by spiderbaby** [comment]
This deprecation warning has been present for years. I will change this since it is confusing. The solution is for the user to specify all the options i.e. make the process_seqtol function call that process_specificity makes with the default arguments.

**Comment by momeara** [comment]
The default arguments are the same between the two functions.

**Comment by spiderbaby** [comment]
Yep, I just noticed - this is fixed now in the repo.
