### ISSUE TITLE
specify input/output files for running sequence tolerance analysis

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#11]

**Comment by spiderbaby** [comment]
Hi,

In analysis/README.rst, the example command line is:

``` R
cd output/sample
R
> source("../../analysis/sequence_tolerance.R")
> process_specificity()
```

This is the way that the original analysis script was written and has been available since the original publication. I'm guessing you've seen the command lines above but would like to specify the input directory and output directory on the command line. We can definitely add this after the paper submission but I would prefer to leave it until after if possible. If you think that this should be done before, I can update the script.

**Comment by momeara** [comment]
Actually, I was just wanted to know what files the script was going to look for and what files it would generate.

**Comment by spiderbaby** [comment]
Ah, understood. I've updated the text:

The main analysis is performed by an R script. Navigate to the directory with the output data from the run and then call this R script _i.e._:

  cd output/sample
  R

> source("../../analysis/sequence_tolerance.R")
> process_seqtol()

The command above uses the default values for process_seqtol. These can be overridden and are, in order:
- the path to the input;
- the fitness function weights (inter- and intra-molecular weights);
- the Boltzmann temperature / sequence cutoff;
- the type of sequence weighting ("boltzmann" or "cutoff");
- the percentile cutoff for merging position weight matrices from different backbone structures;
- plotgen (TRUE or FALSE (default)). If set to TRUE then a a plot similar to Figure 5 in the 2011 ([2]_) manuscript will be produced;
- plotseq (TRUE (default) or FALSE). If set to TRUE then a sequence contribution plot is generated.

See the `Rosetta documentation <https://www.rosettacommons.org/docs/latest/sequence-tolerance.html>`_ or [\ 1_] for more
details. For example, the process_seqtol call above uses the default values and is equivalent to:

> process_seqtol('.', c(1/2.5, 1/2.5, 1/2.5, 1), 0.228, c("boltzmann", "cutoff"), .5, "specificity", FALSE, TRUE)

The input files for the analysis script are generated by the sequence tolerance step:
- 1N7T_{ITERATION}.ga.entities.gz _e.g._ 1N7T_0001.ga.entities.gz;
- 1N7T_{ITERATION}.ga.generations.gz;
- 1N7T_{ITERATION}_seqtol.out;
- the input PDB to the sequence tolerance step (read from _e.g._ 1N7T_{ITERATION}_seqtol.out).

The analysis script currently works with files generated by the Rosetta sequence tolerance application however it can be
modified to work more generally in the event that different sequence tolerance protocols are added to this capture.

By default, the analysis generates the following files:
- specificity_pwm.txt; a position weight matrix;
- specificity_sequences.fasta; a FASTA file which can be used to generate a sequence logo;
- specificity_boxplot_{RESIDUE POSITION}.png; a series of boxplots per designed position;
- specificity_boxplot.pdf/.png; a combined PDF/image of the boxplots above;
- specificity_seqrank.pdf/.png; a predicted ranking table for selected amino acid types for the positions;
- specificity_seqcontrib.pdf; a sequence contribution plot.

For more details, see the Smith & Kortemme 2010 paper (references below).

**Comment by spiderbaby** [comment]
Also, I see that Colin already added an option for input directory (dirpath).
