### ISSUE TITLE
protocols/backrub_seqtol -> Example Overall Command Line

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#12]
# Paths and Extensions

```
WORKING_DIRECTORY=.
BENCHMARK_PATH=<path/to/sequence-tolerance>
# edit protocols/backrub_seqtol/settings.json
```
# Run backrub sequence tolerance in test mode

In _test mode_, it does restricted sampilng to test that the protocol i set up correctly

```
python ${SEQUENCE_TOLERANCE_BASE}/protocols/backrub_seqtol/backrub_seqtol.py ${SEQUENCE_TOLERANCE_BASE}/inputs/pdbs/2I0L_A_C_V2006/2I0L_A_C_V2006.pdb 1 test_mode
```

**Comment by spiderbaby** [comment]
I'm unsure what the bug is in this ticket - are the example command lines wrong?

**Comment by momeara** [comment]
- It should indicate up front what paths and parameters need to be specified by the user.
- The path to the input files is broken
- It should say what "test mode" means

**Comment by spiderbaby** [comment]
Ah, I see. I updated the "Test mode" section to describe what it does in more detail, added explanations for the script parameters, and (hopefully) fixed the paths.
