### ISSUE TITLE
Steps on first page just for testing or is this the full benchmark?

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#13]
The Backrub step generates just a single backrub sampled conformation, right? You should say this and indicate where someone should look for instructions about how to run the full benchmark.

**Comment by spiderbaby** [comment]
Hopefully this is clearer now. I have also added "How to run the full benchmark" sections in both the protocols/backrub_seqtol/README.rst file and the hpc/sge/backrub_seqtol/README.rst.
