### ISSUE TITLE
description of backrub_seqtol.py on front readme seems out of place

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#16]
From "Protocol 1" Section to the end this is all about backrub_seqtol.py. Consider moving/merging it with what you have in protocols/backrub_seqtol/README.rst. 

When you do merge it, make sure use what you introduce. For example, you introduce backrub_seqtol.py but then the example command lines don't use backrub_seqtol.py and instead call the Rosetta code directly.

Similarly move the description of backrub_seqtol from input/README.rst to input/backrub_seqtol/README.rst

**Comment by spiderbaby** [comment]
Agreed - I have merged the documentation into protocols/backrub_seqtol/README.rst.

Also agreed. There is now a greater focus on backrub_seqtol and explicit command lines which can be used to run the complete benchmark. The command lines are not important for most users so I have demoted that section to an Appendix.

Again, agreed. This section has been moved.
