### ISSUE TITLE
Improve description of benchmark and outputs for benchmark

### ISSUE THREAD

**Issue by momeara** [Kortemme-Lab/sequence-tolerance#3]
Each benchmark should clearly state what the benchmark provides, what it requires.

---

The sequence tolerance benchmark measures the recapitulation of a reference distribution over a sequence space given the conformation of a prototypical sequence. This benchmark models, for example, the tolerated sequences of protein-protein interface or protein domain. 

This benchmark includes
- "one sentence description of experimental data"
- Configuration details for the backrub ensemble protocol described in Smith & Kortemme (2010), Smith & Kortemme (2011).
- Analysis scripts that compare a predicted multiple sequence alignment to a reference multiple sequence alignment using 4 recapitulation metrics each based on the position weight matrix estimated for the ensemble.

The full output of a successful run can be found in the 
[RosettaCommons repositories](https://github.com/RosettaCommons/demos/tree/master/protocol_capture/2010/backrub_seqtol) and http://kortemmelab.ucsf.edu/data/.

**Comment by spiderbaby** [comment]
Thanks! I have updated the text.
